str1="bienvenidos a AIPython"
print(f"Cadena original {str1}")
str1=str1.upper()
print(f"Cadena despues de usar la funcion upper {str1}")
str1=str1.lower()
print(f"Cadena despues de usar la funcion lower {str1}")
str1=str1.title()
print(f"Cadena despues de usar la funcion Title {str1}")
print(f"Usando * en cadenas {str1*3}")
print(f"la suma de los numeros es  {2+4}")
